AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  AiSDKFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      MemorySize: 512
      Timeout: 30
      CodeUri: src/handlers/chat
      Handler: index.lambdaHandler
      Runtime: nodejs24.x
      Architectures:
        - x86_64
      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: RESPONSE_STREAM
      Environment:
        Variables:
          LANGFUSE_SECRET_KEY: "{{resolve:secretsmanager:test/langfuse-vercel-ai-sdk:SecretString:langfuse_secret_key}}"
          LANGFUSE_PUBLIC_KEY: "{{resolve:secretsmanager:test/langfuse-vercel-ai-sdk:SecretString:langfuse_public_key}}"
          LANGFUSE_BASE_URL: "{{resolve:secretsmanager:test/langfuse-vercel-ai-sdk:SecretString:langfuse_base_url}}"
      Policies: 
        - arn:aws:iam::aws:policy/AmazonBedrockFullAccess
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - index.ts

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  AiSDKFunction:
    Description: "Lambda Function URL"
    Value: !GetAtt AiSDKFunctionUrl.FunctionUrl
